// frontend-react/src/components/StartGame.tsx
// src/components/StartGame.tsx
import React, { useState } from 'react';
import { startGame } from '../api';

const StartGame = () => {
  const [playerName, setPlayerName] = useState('');

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    const response = await startGame(playerName);
    console.log(response.message); // Or handle this message in the UI
  };

  return (
    <div className="start-game">
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          value={playerName}
          onChange={(e) => setPlayerName(e.target.value)}
          placeholder="Enter Player Name"
        />
        <button type="submit">Start Game</button>
      </form>
    </div>
  );
};

export default StartGame;

// dart-counter-frontend/src/app/start-game/start-game.component.ts
// score-board.component.ts
import { Component } from '@angular/core';
import { GameService } from '../game.service'; // Adjust the path as necessary

@Component({
  selector: 'app-start-game',
  templateUrl: './start-game.component.html',
  styleUrls: ['./start-game.component.css']
})
export class StartGameComponent {
  playerName: string = '';

  constructor(private gameService: GameService) { }

  startGame(): void {
    this.gameService.startGame(this.playerName).subscribe(response => {
      console.log('Game started for:', this.playerName);
      // Handle response, e.g., display player's initial score
    }, error => {
      console.error('Error starting game:', error);
    });
  }
}

<p>start game!</p>
<input [(ngModel)]="playerName" type="text" placeholder="Enter Player Name">
<button (click)="startGame()">Start Game</button>
